### ISSUE TITLE
Computerphile videos attributed to sixtysymbols

### ISSUE THREAD

**Issue by xPMo** [nicktendo64/brady-vs-grey-php#2]
Both current Computerphile videos (Light-field Camera - Computerphile, Pixel Noise (Music from Images) - Computerphile) are attributed to sixtysymbols instead of Computerphile.

**Comment by ncurrault** [comment]
Thanks for pointing that out!
Fixed by commit 66f055bf9c8e74d29a0634d190d3cda825b48601
